# Group wise Analysis

In [5]:
import pandas as pd
# Load data
reviews_df = pd.read_csv('../data/wine-reviews/winemag-data-130k-v2.csv')

In [8]:
# Create a group of reviews of the points of each wine
reviews_df.groupby('points').points.count()

# value_counts() is just a shortcut to the groupby() operation

points
80       397
81       692
82      1836
83      3025
84      6480
85      9530
86     12600
87     16933
88     17207
89     12226
90     15410
91     11359
92      9613
93      6489
94      3758
95      1535
96       523
97       229
98        77
99        33
100       19
Name: points, dtype: int64

In [12]:
# Get the Cheapest wine in each point value category
reviews_df.groupby('points').price.min()

points
80      5.0
81      5.0
82      4.0
83      4.0
84      4.0
85      4.0
86      4.0
87      5.0
88      6.0
89      7.0
90      8.0
91      7.0
92     11.0
93     12.0
94     13.0
95     20.0
96     20.0
97     35.0
98     50.0
99     44.0
100    80.0
Name: price, dtype: float64

In [14]:
# Use the apply() method to access the DataFrame filter data
reviews_df.groupby('winery').apply(lambda df: df.title.iloc[0])

C:\Users\white\AppData\Local\Temp\ipykernel_4316\2646945333.py:2: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  reviews_df.groupby('winery').apply(lambda df: df.title.iloc[0])

winery
1+1=3                                     1+1=3 NV Rosé Sparkling (Cava)
10 Knots                            10 Knots 2010 Viognier (Paso Robles)
100 Percent Wine              100 Percent Wine 2015 Moscato (California)
1000 Stories           1000 Stories 2013 Bourbon Barrel Aged Zinfande...
1070 Green                  1070 Green 2011 Sauvignon Blanc (Rutherford)
                                             ...
Órale                       Órale 2011 Cabronita Red (Santa Ynez Valley)
Öko                    Öko 2013 Made With Organically Grown Grapes Ma...
Ökonomierat Rebholz    Ökonomierat Rebholz 2007 Von Rotliegenden Spät...
àMaurice               àMaurice 2013 Fred Estate Syrah (Walla Walla V...
Štoka                                    Štoka 2009 Izbrani Teran (Kras)
Length: 16757, dtype: object

In [20]:
# More fine grained control you can group by more than one column
reviews_df.groupby(['country','province','winery']).apply(lambda df: df.loc[df.points.idxmax()])

C:\Users\white\AppData\Local\Temp\ipykernel_4316\4278998912.py:2: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  reviews_df.groupby(['country','province','winery']).apply(lambda df: df.loc[df.points.idxmax()])

                                             Unnamed: 0    country  \
country   province         winery
Argentina Mendoza Province 2 Copas                 5902  Argentina
                           Achaval-Ferrer         22371  Argentina
                           Aconcagua              64649  Argentina
                           Aconga                 95875  Argentina
                           Acordeón               37485  Argentina
...                                                 ...        ...
Uruguay   Uruguay          Familia Traversa      111956    Uruguay
                           Garzón                113525    Uruguay
                           Gimenez Mendez         82564    Uruguay
                           Narbona                39361    Uruguay
                           Pizzorno               98839    Uruguay

                                                                                   description  \
country   province         winery
Argentina Mendoza Province 2 Copas           Smells like wet dog, with sweaty red fruit. Th...
                           Achaval-Ferrer    Earthy berry aromas are complex due to side no...
                           Aconcagua         Stemmy on the nose, with aromas of rhubarb, pi...
                           Aconga            Floral and citrusy smelling, with a lightness ...
                           Acordeón          Candied cherry aromas are mildly rubbery and s...
...                                                                                        ...
Uruguay   Uruguay          Familia Traversa  Woody berry aromas are solid but standard. Thi...
                           Garzón            Aromas of tea, tomato and Chinese spices accen...
                           Gimenez Mendez    Warm baked aromas of oak resin and spice cake ...
                           Narbona           Cherry and berry aromas are ripe, healthy and ...
                           Pizzorno          Spicy oak aromas suggest sandalwood, while thi...

                                                                              designation  \
country   province         winery
Argentina Mendoza Province 2 Copas                                                    NaN
                           Achaval-Ferrer                               Finca Bella Vista
                           Aconcagua                                              Reserve
                           Aconga                                                     NaN
                           Acordeón                                                   NaN
...                                                                                   ...
Uruguay   Uruguay          Familia Traversa  Noble Alianza Reserva Marselan-Tannat-Merlot
                           Garzón                                         Single Vineyard
                           Gimenez Mendez                                    Alta Reserva
                           Narbona                              Blend 002 Limited Edition
                           Pizzorno                                                 Primo

                                             points  price          province  \
country   province         winery
Argentina Mendoza Province 2 Copas               81    8.0  Mendoza Province
                           Achaval-Ferrer        94  140.0  Mendoza Province
                           Aconcagua             84   15.0  Mendoza Province
                           Aconga                85    9.0  Mendoza Province
                           Acordeón              86    9.0  Mendoza Province
...                                             ...    ...               ...
Uruguay   Uruguay          Familia Traversa      85   13.0           Uruguay
                           Garzón                90   30.0           Uruguay
                           Gimenez Mendez        88   23.0           Uruguay
                           Narbona               91   22.0           Uruguay
                           Pizzorno              91   50.0           Uruguay

                                              region_1 region_2  \
country   province         winery
Argentina Mendoza Province 2 Copas             Mendoza      NaN
                           Achaval-Ferrer      Mendoza      NaN
                           Aconcagua           Mendoza      NaN
                           Aconga              Mendoza      NaN
                           Acordeón          Tupungato      NaN
...                                                ...      ...
Uruguay   Uruguay          Familia Traversa        NaN      NaN
                           Garzón                  NaN      NaN
                           Gimenez Mendez          NaN      NaN
                           Narbona                 NaN      NaN
                           Pizzorno                NaN      NaN

                                                   taster_name  \
country   province         winery
Argentina Mendoza Province 2 Copas           Michael Schachner
                           Achaval-Ferrer    Michael Schachner
                           Aconcagua         Michael Schachner
                           Aconga            Michael Schachner
                           Acordeón          Michael Schachner
...                                                        ...
Uruguay   Uruguay          Familia Traversa  Michael Schachner
                           Garzón            Michael Schachner
                           Gimenez Mendez    Michael Schachner
                           Narbona           Michael Schachner
                           Pizzorno          Michael Schachner

                                            taster_twitter_handle  \
country   province         winery
Argentina Mendoza Province 2 Copas                    @wineschach
                           Achaval-Ferrer             @wineschach
                           Aconcagua                  @wineschach
                           Aconga                     @wineschach
                           Acordeón                   @wineschach
...                                                           ...
Uruguay   Uruguay          Familia Traversa           @wineschach
                           Garzón                     @wineschach
                           Gimenez Mendez             @wineschach
                           Narbona                    @wineschach
                           Pizzorno                   @wineschach

                                                                                         title  \
country   province         winery
Argentina Mendoza Province 2 Copas                                  2 Copas 2009 Red (Mendoza)
                           Achaval-Ferrer    Achaval-Ferrer 2014 Finca Bella Vista Malbec (...
                           Aconcagua                   Aconcagua 2005 Reserve Malbec (Mendoza)
                           Aconga                Aconga 2011 Chenin Blanc-Chardonnay (Mendoza)
                           Acordeón                           Acordeón 2011 Malbec (Tupungato)
...                                                                                        ...
Uruguay   Uruguay          Familia Traversa  Familia Traversa 2015 Noble Alianza Reserva Ma...
                           Garzón             Garzón 2015 Single Vineyard Pinot Noir (Uruguay)
                           Gimenez Mendez    Gimenez Mendez 2015 Alta Reserva Tannat (Uruguay)
                           Narbona           Narbona NV Blend 002 Limited Edition Tannat-Ca...
                           Pizzorno                          Pizzorno 2011 Primo Red (Uruguay)

                                                             variety  \
country   province         winery
Argentina Mendoza Province 2 Copas                         Red Blend
                           Achaval-Ferrer                     Malbec
                           Aconcagua                          Malbec
                           Aconga            Chenin Blanc-Chardonnay
                           Acordeón                           Malbec
...                                                              ...
Uruguay   Uruguay          Familia Traversa                Red Blend
                           Garzón                         Pinot Noir
                           Gimenez Mendez                     Tannat
                           Narbona             Tannat-Cabernet Franc
                           Pizzorno                        Red Blend

                                                       winery
country   province         winery
Argentina Mendoza Province 2 Copas                    2 Copas
                           Achaval-Ferrer      Achaval-Ferrer
                           Aconcagua                Aconcagua
                           Aconga                      Aconga
                           Acordeón                  Acordeón
...                                                       ...
Uruguay   Uruguay          Familia Traversa  Familia Traversa
                           Garzón                      Garzón
                           Gimenez Mendez      Gimenez Mendez
                           Narbona                    Narbona
                           Pizzorno                  Pizzorno

[19028 rows x 14 columns]

In [33]:
# Use the agg() function to run a lot of different functions in your DataFrame
reviews_df.groupby(['country']).price.agg([len,"min","max"])

                          len   min     max
country
Argentina                3800   4.0   230.0
Armenia                     2  14.0    15.0
Australia                2329   5.0   850.0
Austria                  3345   7.0  1100.0
Bosnia and Herzegovina      2  12.0    13.0
Brazil                     52  10.0    60.0
Bulgaria                  141   8.0   100.0
Canada                    257  12.0   120.0
Chile                    4472   5.0   400.0
China                       1  18.0    18.0
Croatia                    73  12.0    65.0
Cyprus                     11  11.0    21.0
Czech Republic             12  15.0    45.0
Egypt                       1   NaN     NaN
England                    74  25.0    95.0
France                  22093   5.0  3300.0
Georgia                    86   9.0    40.0
Germany                  2165   5.0   775.0
Greece                    466   8.0    79.0
Hungary                   146  10.0   764.0
India                       9  10.0    20.0
Israel                    505   8.0   150.0
Italy                   19540   5.0   900.0
Lebanon                    35  13.0    75.0
Luxembourg                  6  16.0    30.0
Macedonia                  12  15.0    20.0
Mexico                     70   8.0   108.0
Moldova                    59   8.0    42.0
Morocco                    28  14.0    40.0
New Zealand              1419   7.0   130.0
Peru                       16  10.0    68.0
Portugal                 5691   5.0  1000.0
Romania                   120   4.0   320.0
Serbia                     12  15.0    42.0
Slovakia                    1  16.0    16.0
Slovenia                   87   7.0    90.0
South Africa             1401   5.0   330.0
Spain                    6645   4.0   770.0
Switzerland                 7  21.0   160.0
Turkey                     90  14.0   120.0
US                      54504   4.0  2013.0
Ukraine                    14   6.0    13.0
Uruguay                   109  10.0   130.0

## Multi-Indexes

In [40]:
# Multi-index differs from regular index in that it has multiple levels
country_reviewed = reviews_df.groupby(['country','province']).description.agg([len])
mi = country_reviewed.index # check how many indexes you have in df
print(type(mi))
country_reviewed

<class 'pandas.core.indexes.multi.MultiIndex'>

                             len
country   province
Argentina Mendoza Province  3264
          Other              536
Armenia   Armenia              2
Australia Australia Other    245
          New South Wales     85
...                          ...
Uruguay   Juanico             12
          Montevideo          11
          Progreso            11
          San Jose             3
          Uruguay             24

[425 rows x 1 columns]

In [42]:
# You need to reset the index to add it back into the multi-index df
country_reviewed.reset_index()

       country          province   len
0    Argentina  Mendoza Province  3264
1    Argentina             Other   536
2      Armenia           Armenia     2
3    Australia   Australia Other   245
4    Australia   New South Wales    85
..         ...               ...   ...
420    Uruguay           Juanico    12
421    Uruguay        Montevideo    11
422    Uruguay          Progreso    11
423    Uruguay          San Jose     3
424    Uruguay           Uruguay    24

[425 rows x 3 columns]

In [45]:
# Sort by value
country_reviewed = country_reviewed.reset_index()
# Default is ascending = True
country_reviewed.sort_values(by='len', ascending=False)

     index       country         province    len
392    392            US       California  36247
415    415            US       Washington   8639
118    118        France         Bordeaux   5941
227    227         Italy          Tuscany   5897
409    409            US           Oregon   5373
..     ...           ...              ...    ...
101    101       Croatia              Krk      1
247    247   New Zealand        Gladstone      1
357    357  South Africa  Piekenierskloof      1
63      63         Chile          Coelemu      1
149    149        Greece           Beotia      1

[425 rows x 4 columns]